name: Publish latest to docker

on:
  push:
    branches:
      - master

jobs:

  release:
    if: github.repository == 'PasteUs/PasteMeFrontend'
    name: Build with node ${{ matrix.node_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [12.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: build and update cdn
        run: |
          GH_TOKEN=${{ secrets.GITHUB_PASSWORD }} bash .github/shell/build_and_update_cdn.sh

      - name: publish docker
        uses: LucienShui/Publish-Docker-Github-Action@2.7.1
        with:
          name: registry.cn-hangzhou.aliyuncs.com/pasteus/pasteme-frontend:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-hangzhou.aliyuncs.com
          dockerfile: Dockerfile

      - name: trigger webhook
        run: |
          curl -X POST ${{ secrets.MASTER_WEBHOOK }}

      - name: update LucienShui/PasteMe@dev
        run: |
          GH_TOKEN=${{ secrets.GITHUB_PASSWORD }} bash .github/shell/pasteme_dev_update.sh